spring.application.name=pizza-monolith
server.port=${PORT:8080}

# Database Config (Supports MySQL and PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:pizzastore}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:aniketpandeyji1221@gmail.com}
spring.mail.password=${MAIL_PASSWORD:tdxevysmmsrlyfgm}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Inter-Service URLs (Routing all requests to localhost itself)
user.service.url=${USER_SERVICE_URL:http://localhost:8080}
admin.service.url=${ADMIN_SERVICE_URL:http://localhost:8080}
order.service.url=${ORDER_SERVICE_URL:http://localhost:8080}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8080}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8080}
